[tool.poetry]
name = "facial"
version = "0.1.0"
description = ""
authors = ["you"]

[tool.poetry.dependencies]
python = "3.10.*"
flask = "3.1.2"
opencv-python-headless = "4.12.0.88"
mediapipe = "0.10.7"
